services:
  - type: web
    name: jabe-calculator
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: USERS
        sync: false
      - key: GMAIL_USER
        sync: false
      - key: GMAIL_PASSWORD
        sync: false
